version: "3.9"
services:
    web_api:
        build: 
            context: .
            dockerfile: src/Hera.WebApi/Dockerfile  
        environment:
            - "ConnectionStrings__HeraDatabase=Server=localhost;Database=Hera;User=sa;Password=Pa55w0rd2022;MultipleActiveResultSets=true"
            # - ASPNETCORE_URLS=https://+:443;http://+:80
            # - "ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd"
            # - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
        ports:
            - "8000:80"
            # - "8001:443"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pa55w0rd2022"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
