version: "3.9"
services:
    web_api:
        build: 
            context: .
            dockerfile: src/Hera.WebApi/Dockerfile  
        environment:
            - "ConnectionStrings__HeraDatabase=Server=db;Database=Hera;User=sa;Password=Pa55w0rd2022;MultipleActiveResultSets=true"
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pa55w0rd2022"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
