version: "3.9"
services:
    web_api:
        build: ./src/Hera.WebApi
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "123456"
            ACCEPT_EULA: "Y"